amcl:
  ros__parameters:
    use_map_topic: true
    map_topic: /map
    base_frame_id: base_footprint
    global_frame_id: map
    odom_frame_id: odom
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.2
    laser_likelihood_max_dist: 2.0
    transform_tolerance: 0.5
    use_sim_time: false  # Set to true if using simulation time
    initial_pose_x: 1.0  # Set your initial x position
    initial_pose_y: 1.0  # Set your initial y position
    initial_pose_a: 0.0   # Set your initial orientation (radians)