global_costmap:
 # Utilize costmaps that are updated in real-time based on LIDAR data to represent the environment and detect obstacles.
 # Obstacle Layer: Marks occupied spaces based on LIDAR readings.
 # Inflation Layer: Expands the occupied areas to create a buffer zone around obstacles, preventing the robot from getting too close.
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true
  plugins:
    - {name: static_layer, type: "nav2_costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan
  laser_scan:
    data_type: "sensor_msgs/msg/LaserScan"
    topic: "/scan"  # Change this to your LIDAR topic
    marking: true
    clearing: true
    expected_update_rate: 0.5

inflation_layer:
  inflation_radius: 0.5
  cost_scaling_factor: 10.0