dwb_controller:

# DWB is generally simpler and works well for many applications, especially when the environment is not too complex or dynamic.
  plugin: "dwb_local_planner/DWBLocalPlanner" # DWB (Dynamic Window Approach) and TEB (Timed Elastic Band)
  # DWB specific parameters
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 20
  min_vel_x: 0.0
  max_vel_x: 0.1
  min_vel_y: -0.1
  max_vel_y: 0.1
  min_vel_theta: -0.1
  max_vel_theta: 0.1
  # Add other parameters as needed
  # Cost parameters
  cost_scaling_factor: 10.0
  # Add other parameters as needed