amcl:
  ros__parameters:
    use_sim_time: false  # Set to true if using simulation
    min_particles: 500  # Minimum number of particles
    max_particles: 2000  # Maximum number of particles
    kld_err: 0.05        # KLD error
    kld_z: 0.99          # KLD z value
    update_min_d: 0.2    # Minimum distance to update
    update_min_a: 0.5    # Minimum angle to update
    transform_tolerance: 0.0  # Tolerance for transforms
    laser_likelihood_max_dist: 2.0
    initial_pose_x: 0.0  # Initial pose x
    initial_pose_y: 0.0  # Initial pose y
    initial_pose_a: 0.0  # Initial pose angle
    # Additional parameters can be added here
    use_map_topic: true
    map_topic: /map
    base_frame_id: base_footprint
    global_frame_id: map
    odom_frame_id: odom
    

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map_1733563821.yaml"

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False


robot_state_publisher:
  ros__parameters:
    use_sim_time: false